{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cd-manager.fullname" . }}
  labels:
    {{- include "cd-manager.labels" . | nindent 4 }}
type: Opaque
data:
  AUTH_SECRET: {{ .Values.secrets.authSecret | b64enc | quote }}
  DISCOGS_USER_TOKEN: {{ .Values.secrets.discogsUserToken | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
{{- end -}}
