# secrets.yaml (DO NOT COMMIT THIS FILE)
# Use this file to store sensitive information.
# Deploy with: helm install cd-manager ./charts/cd-manager -f values.yaml -f secrets.yaml

secrets:
  # Helm will create a Secret resource with these values
  authSecret: "YOUR_GENERATED_AUTH_SECRET"
  discogsUserToken: "YOUR_DISCOGS_TOKEN"
  googleClientId: "YOUR_GOOGLE_CLIENT_ID"
  googleClientSecret: "YOUR_GOOGLE_CLIENT_SECRET"
